# Generated by Django 6.0.2 on 2026-03-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_wallettransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='spending_limit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional debit spending limit set by user', max_digits=15, null=True),
        ),
    ]
